var myObject = {
    "unosfumes": [{
        "img-src": "ico.png",
        "strong": "Slam",
        "fecha-De-Publicacion": "<time datetime='2022-03-28T02:04:18.929Z'>Domingo 05 de marzo 2022 </time>",
        "a-href": "guia.html",
        "a-href-tittle": "Slamming Guía para la reducción de daños asociados al uso de las drogas inyectables",
        "how-to-tittle": "Slamming Guía para la reducción de daños asociados al uso de las drogas inyectables ",
        "el-Post": " Slamming Guía para la reducción de daños asociados al uso de las drogas inyectables ",
        "accion": "Ver ahora",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "strong": "Cristal",
        "fecha-De-Publicacion": "<time datetime='2022-03-28T02:04:18.929Z'>Sábado 28 agosto 2021</time>",
        "a-href": "diamante-meth.html",
        "a-href-tittle": "Pero el hubiera no existe",
        "how-to-tittle": "Lo que me hubiera gustado",
        "el-Post": " Diamante Meth ",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "strong": "Cristal",
        "fecha-De-Publicacion": "<time datetime='2022-03-28T02:04:18.929Z'>Sábado 28 agosto 2021</time>",
        "a-href": "Walter-White-Blue-Meth.html",
        "a-href-tittle": "Pero el hubiera no existe",
        "how-to-tittle": "Lo que me hubiera gustado",
        "el-Post": " Breaking Bad - Walter White Blue Meth ",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, {
        "img-src": "ico.png",
        "strong": "Cristal",
        "fecha-De-Publicacion": "<time datetime='2022-03-28T02:04:18.929Z'>Sábado 28 agosto 2021</time>",
        "a-href": "meth.html",
        "a-href-tittle": "Pero el hubiera no existe",
        "how-to-tittle": "Lo que me hubiera gustado",
        "el-Post": "Lo que me hubiera gustado saber del cristal antes de haberlo fumado por primera vez - ",
        "accion": "Ver",
        "postFoto1": "",
        "altPostFoto1": "",
        "postFoto2": " ",
        "altPostFoto2": "",
        "postFoto3": "",
        "altPostFoto3": "",
        "postFoto4": "",
        "altPostFoto4": "",
        "score-lighthouse": "",
        "img-score-lighthouse": "",
    }, ]
};

w3.displayObject("siteMap", myObject);